/**
 * @generated — do not edit this script output; edit this script instead.
 *
 * Generates: src/features/schema-form/registry.generated.ts
 *
 * Run via: bun run gen:widgets
 * Idempotent: running twice produces no diff.
 */

import { writeFileSync } from "node:fs"
import { basename, join } from "node:path"

const schemaFormDir = join(import.meta.dir, "../src/features/schema-form")
const widgetsGlob = new Bun.Glob("widgets/*.tsx")
const widgetFiles = Array.from(widgetsGlob.scanSync(schemaFormDir)).sort()

const lines: string[] = [
	"// AUTO-GENERATED by scripts/gen-widget-registry.ts — do not edit.",
	"// Run `bun run gen:widgets` to regenerate.",
	"// @generated",
	"",
	'import type React from "react"',
	'import type { WidgetProps } from "./types"',
]

const names: string[] = []
for (const file of widgetFiles) {
	const name = basename(file, ".tsx")
	names.push(name)
	lines.push(`import ${name}Widget from "./widgets/${name}"`)
}

lines.push("")
if (names.length > 0) {
	lines.push(
		`export type WidgetName = ${names.map((n) => JSON.stringify(n)).join(" | ")}`,
	)
} else {
	lines.push("export type WidgetName = never")
}
lines.push("")
lines.push(
	"export const widgetRegistry: Record<WidgetName, React.ComponentType<WidgetProps>> = {",
)
for (const name of names) {
	lines.push(`\t${name}: ${name}Widget,`)
}
lines.push("}")
lines.push("")

const content = lines.join("\n")
const outPath = join(schemaFormDir, "registry.generated.ts")
writeFileSync(outPath, content)
console.log(`Wrote ${outPath}`)
