/**
 * @generated — do not edit this script output; edit this script instead.
 *
 * Generates: src/components/project-canvas/nodes/registry.generated.ts
 *
 * Run via: bun run gen:canvas-nodes
 * Idempotent: running twice produces no diff.
 */

import { writeFileSync } from "node:fs"
import { basename, join } from "node:path"

const EXCLUDE = new Set([
	"ResourceNode.tsx",
	"ResourceNodeHeader.tsx",
	"ContainerNode.tsx",
	"GroupNode.tsx",
	"registry.generated.ts",
])

const nodesDir = join(import.meta.dir, "../src/components/project-canvas/nodes")
const glob = new Bun.Glob("*.tsx")
const files = Array.from(glob.scanSync(nodesDir))
	.filter((f) => !EXCLUDE.has(f))
	.sort()

const lines: string[] = [
	"// AUTO-GENERATED by scripts/gen-canvas-nodes.ts — do not edit.",
	"// Run `bun run gen:canvas-nodes` to regenerate.",
	"// @generated",
	'import type { ComponentType } from "react"',
	'import type { NodeProps } from "@xyflow/react"',
	"",
	"export type CanvasNodeComponent = ComponentType<NodeProps>",
]

const names: string[] = []
for (const file of files) {
	const name = basename(file, ".tsx")
	names.push(name)
	lines.push(`import ${name} from "./${name}"`)
}

lines.push("")
lines.push("export const customNodes: Record<string, CanvasNodeComponent> = {")
for (const name of names) {
	lines.push(`\t${name},`)
}
if (names.length === 0) {
	lines.push(
		"\t// populated when files like aws_rds_cluster.tsx exist in this dir",
	)
}
lines.push("}")
lines.push("")

const content = lines.join("\n")
const outPath = join(nodesDir, "registry.generated.ts")
writeFileSync(outPath, content)
console.log(`Wrote ${outPath}`)
