/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TermsRouteImport } from "./routes/terms"
import { Route as PrivacyRouteImport } from "./routes/privacy"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as DeviceRouteImport } from "./routes/device"
import { Route as AuthedRouteImport } from "./routes/_authed"
import { Route as AppRouteImport } from "./routes/_app"
import { Route as AppIndexRouteImport } from "./routes/_app/index"
import { Route as AcceptInvitationIdRouteImport } from "./routes/accept-invitation/$id"
import { Route as AuthedOnboardingRouteImport } from "./routes/_authed/onboarding"
import { Route as AppConsentRouteImport } from "./routes/_app/consent"
import { Route as AppProjectsIndexRouteImport } from "./routes/_app/projects/index"
import { Route as AppMembersIndexRouteImport } from "./routes/_app/members/index"
import { Route as AppSettingsProfileRouteImport } from "./routes/_app/settings/profile"
import { Route as AppSettingsOrganizationRouteImport } from "./routes/_app/settings/organization"
import { Route as AppSettingsApiKeysRouteImport } from "./routes/_app/settings/api-keys"
import { Route as AppProjectsProjectSlugRouteImport } from "./routes/_app/projects/$projectSlug"
import { Route as AppProjectsProjectSlugIndexRouteImport } from "./routes/_app/projects/$projectSlug/index"
import { Route as AppProjectsProjectSlugSettingsIndexRouteImport } from "./routes/_app/projects/$projectSlug/settings/index"
import { Route as AppProjectsProjectSlugIntegrationsIndexRouteImport } from "./routes/_app/projects/$projectSlug/integrations/index"
import { Route as AppProjectsProjectSlugArchitectureIndexRouteImport } from "./routes/_app/projects/$projectSlug/architecture/index"
import { Route as AppProjectsProjectSlugResourcesResourceSlugIndexRouteImport } from "./routes/_app/projects/$projectSlug/resources/$resourceSlug/index"

const TermsRoute = TermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: "/device",
  path: "/device",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: "/accept-invitation/$id",
  path: "/accept-invitation/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => AuthedRoute,
} as any)
const AppConsentRoute = AppConsentRouteImport.update({
  id: "/consent",
  path: "/consent",
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => AppRoute,
} as any)
const AppMembersIndexRoute = AppMembersIndexRouteImport.update({
  id: "/members/",
  path: "/members/",
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: "/settings/profile",
  path: "/settings/profile",
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsOrganizationRoute = AppSettingsOrganizationRouteImport.update({
  id: "/settings/organization",
  path: "/settings/organization",
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: "/settings/api-keys",
  path: "/settings/api-keys",
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectSlugRoute = AppProjectsProjectSlugRouteImport.update({
  id: "/projects/$projectSlug",
  path: "/projects/$projectSlug",
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectSlugIndexRoute =
  AppProjectsProjectSlugIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)
const AppProjectsProjectSlugSettingsIndexRoute =
  AppProjectsProjectSlugSettingsIndexRouteImport.update({
    id: "/settings/",
    path: "/settings/",
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)
const AppProjectsProjectSlugIntegrationsIndexRoute =
  AppProjectsProjectSlugIntegrationsIndexRouteImport.update({
    id: "/integrations/",
    path: "/integrations/",
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)
const AppProjectsProjectSlugArchitectureIndexRoute =
  AppProjectsProjectSlugArchitectureIndexRouteImport.update({
    id: "/architecture/",
    path: "/architecture/",
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)
const AppProjectsProjectSlugResourcesResourceSlugIndexRoute =
  AppProjectsProjectSlugResourcesResourceSlugIndexRouteImport.update({
    id: "/resources/$resourceSlug/",
    path: "/resources/$resourceSlug/",
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute
  "/device": typeof DeviceRoute
  "/login": typeof LoginRoute
  "/privacy": typeof PrivacyRoute
  "/terms": typeof TermsRoute
  "/consent": typeof AppConsentRoute
  "/onboarding": typeof AuthedOnboardingRoute
  "/accept-invitation/$id": typeof AcceptInvitationIdRoute
  "/projects/$projectSlug": typeof AppProjectsProjectSlugRouteWithChildren
  "/settings/api-keys": typeof AppSettingsApiKeysRoute
  "/settings/organization": typeof AppSettingsOrganizationRoute
  "/settings/profile": typeof AppSettingsProfileRoute
  "/members/": typeof AppMembersIndexRoute
  "/projects/": typeof AppProjectsIndexRoute
  "/projects/$projectSlug/": typeof AppProjectsProjectSlugIndexRoute
  "/projects/$projectSlug/architecture/": typeof AppProjectsProjectSlugArchitectureIndexRoute
  "/projects/$projectSlug/integrations/": typeof AppProjectsProjectSlugIntegrationsIndexRoute
  "/projects/$projectSlug/settings/": typeof AppProjectsProjectSlugSettingsIndexRoute
  "/projects/$projectSlug/resources/$resourceSlug/": typeof AppProjectsProjectSlugResourcesResourceSlugIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof AppIndexRoute
  "/device": typeof DeviceRoute
  "/login": typeof LoginRoute
  "/privacy": typeof PrivacyRoute
  "/terms": typeof TermsRoute
  "/consent": typeof AppConsentRoute
  "/onboarding": typeof AuthedOnboardingRoute
  "/accept-invitation/$id": typeof AcceptInvitationIdRoute
  "/settings/api-keys": typeof AppSettingsApiKeysRoute
  "/settings/organization": typeof AppSettingsOrganizationRoute
  "/settings/profile": typeof AppSettingsProfileRoute
  "/members": typeof AppMembersIndexRoute
  "/projects": typeof AppProjectsIndexRoute
  "/projects/$projectSlug": typeof AppProjectsProjectSlugIndexRoute
  "/projects/$projectSlug/architecture": typeof AppProjectsProjectSlugArchitectureIndexRoute
  "/projects/$projectSlug/integrations": typeof AppProjectsProjectSlugIntegrationsIndexRoute
  "/projects/$projectSlug/settings": typeof AppProjectsProjectSlugSettingsIndexRoute
  "/projects/$projectSlug/resources/$resourceSlug": typeof AppProjectsProjectSlugResourcesResourceSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_app": typeof AppRouteWithChildren
  "/_authed": typeof AuthedRouteWithChildren
  "/device": typeof DeviceRoute
  "/login": typeof LoginRoute
  "/privacy": typeof PrivacyRoute
  "/terms": typeof TermsRoute
  "/_app/consent": typeof AppConsentRoute
  "/_authed/onboarding": typeof AuthedOnboardingRoute
  "/accept-invitation/$id": typeof AcceptInvitationIdRoute
  "/_app/": typeof AppIndexRoute
  "/_app/projects/$projectSlug": typeof AppProjectsProjectSlugRouteWithChildren
  "/_app/settings/api-keys": typeof AppSettingsApiKeysRoute
  "/_app/settings/organization": typeof AppSettingsOrganizationRoute
  "/_app/settings/profile": typeof AppSettingsProfileRoute
  "/_app/members/": typeof AppMembersIndexRoute
  "/_app/projects/": typeof AppProjectsIndexRoute
  "/_app/projects/$projectSlug/": typeof AppProjectsProjectSlugIndexRoute
  "/_app/projects/$projectSlug/architecture/": typeof AppProjectsProjectSlugArchitectureIndexRoute
  "/_app/projects/$projectSlug/integrations/": typeof AppProjectsProjectSlugIntegrationsIndexRoute
  "/_app/projects/$projectSlug/settings/": typeof AppProjectsProjectSlugSettingsIndexRoute
  "/_app/projects/$projectSlug/resources/$resourceSlug/": typeof AppProjectsProjectSlugResourcesResourceSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/device"
    | "/login"
    | "/privacy"
    | "/terms"
    | "/consent"
    | "/onboarding"
    | "/accept-invitation/$id"
    | "/projects/$projectSlug"
    | "/settings/api-keys"
    | "/settings/organization"
    | "/settings/profile"
    | "/members/"
    | "/projects/"
    | "/projects/$projectSlug/"
    | "/projects/$projectSlug/architecture/"
    | "/projects/$projectSlug/integrations/"
    | "/projects/$projectSlug/settings/"
    | "/projects/$projectSlug/resources/$resourceSlug/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/device"
    | "/login"
    | "/privacy"
    | "/terms"
    | "/consent"
    | "/onboarding"
    | "/accept-invitation/$id"
    | "/settings/api-keys"
    | "/settings/organization"
    | "/settings/profile"
    | "/members"
    | "/projects"
    | "/projects/$projectSlug"
    | "/projects/$projectSlug/architecture"
    | "/projects/$projectSlug/integrations"
    | "/projects/$projectSlug/settings"
    | "/projects/$projectSlug/resources/$resourceSlug"
  id:
    | "__root__"
    | "/_app"
    | "/_authed"
    | "/device"
    | "/login"
    | "/privacy"
    | "/terms"
    | "/_app/consent"
    | "/_authed/onboarding"
    | "/accept-invitation/$id"
    | "/_app/"
    | "/_app/projects/$projectSlug"
    | "/_app/settings/api-keys"
    | "/_app/settings/organization"
    | "/_app/settings/profile"
    | "/_app/members/"
    | "/_app/projects/"
    | "/_app/projects/$projectSlug/"
    | "/_app/projects/$projectSlug/architecture/"
    | "/_app/projects/$projectSlug/integrations/"
    | "/_app/projects/$projectSlug/settings/"
    | "/_app/projects/$projectSlug/resources/$resourceSlug/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
  DeviceRoute: typeof DeviceRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/terms": {
      id: "/terms"
      path: "/terms"
      fullPath: "/terms"
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/privacy": {
      id: "/privacy"
      path: "/privacy"
      fullPath: "/privacy"
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/device": {
      id: "/device"
      path: "/device"
      fullPath: "/device"
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed": {
      id: "/_authed"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/": {
      id: "/_app/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/accept-invitation/$id": {
      id: "/accept-invitation/$id"
      path: "/accept-invitation/$id"
      fullPath: "/accept-invitation/$id"
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed/onboarding": {
      id: "/_authed/onboarding"
      path: "/onboarding"
      fullPath: "/onboarding"
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_app/consent": {
      id: "/_app/consent"
      path: "/consent"
      fullPath: "/consent"
      preLoaderRoute: typeof AppConsentRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/projects/": {
      id: "/_app/projects/"
      path: "/projects"
      fullPath: "/projects/"
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/members/": {
      id: "/_app/members/"
      path: "/members"
      fullPath: "/members/"
      preLoaderRoute: typeof AppMembersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/settings/profile": {
      id: "/_app/settings/profile"
      path: "/settings/profile"
      fullPath: "/settings/profile"
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/settings/organization": {
      id: "/_app/settings/organization"
      path: "/settings/organization"
      fullPath: "/settings/organization"
      preLoaderRoute: typeof AppSettingsOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/settings/api-keys": {
      id: "/_app/settings/api-keys"
      path: "/settings/api-keys"
      fullPath: "/settings/api-keys"
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/projects/$projectSlug": {
      id: "/_app/projects/$projectSlug"
      path: "/projects/$projectSlug"
      fullPath: "/projects/$projectSlug"
      preLoaderRoute: typeof AppProjectsProjectSlugRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/projects/$projectSlug/": {
      id: "/_app/projects/$projectSlug/"
      path: "/"
      fullPath: "/projects/$projectSlug/"
      preLoaderRoute: typeof AppProjectsProjectSlugIndexRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
    "/_app/projects/$projectSlug/settings/": {
      id: "/_app/projects/$projectSlug/settings/"
      path: "/settings"
      fullPath: "/projects/$projectSlug/settings/"
      preLoaderRoute: typeof AppProjectsProjectSlugSettingsIndexRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
    "/_app/projects/$projectSlug/integrations/": {
      id: "/_app/projects/$projectSlug/integrations/"
      path: "/integrations"
      fullPath: "/projects/$projectSlug/integrations/"
      preLoaderRoute: typeof AppProjectsProjectSlugIntegrationsIndexRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
    "/_app/projects/$projectSlug/architecture/": {
      id: "/_app/projects/$projectSlug/architecture/"
      path: "/architecture"
      fullPath: "/projects/$projectSlug/architecture/"
      preLoaderRoute: typeof AppProjectsProjectSlugArchitectureIndexRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
    "/_app/projects/$projectSlug/resources/$resourceSlug/": {
      id: "/_app/projects/$projectSlug/resources/$resourceSlug/"
      path: "/resources/$resourceSlug"
      fullPath: "/projects/$projectSlug/resources/$resourceSlug/"
      preLoaderRoute: typeof AppProjectsProjectSlugResourcesResourceSlugIndexRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
  }
}

interface AppProjectsProjectSlugRouteChildren {
  AppProjectsProjectSlugIndexRoute: typeof AppProjectsProjectSlugIndexRoute
  AppProjectsProjectSlugArchitectureIndexRoute: typeof AppProjectsProjectSlugArchitectureIndexRoute
  AppProjectsProjectSlugIntegrationsIndexRoute: typeof AppProjectsProjectSlugIntegrationsIndexRoute
  AppProjectsProjectSlugSettingsIndexRoute: typeof AppProjectsProjectSlugSettingsIndexRoute
  AppProjectsProjectSlugResourcesResourceSlugIndexRoute: typeof AppProjectsProjectSlugResourcesResourceSlugIndexRoute
}

const AppProjectsProjectSlugRouteChildren: AppProjectsProjectSlugRouteChildren =
  {
    AppProjectsProjectSlugIndexRoute: AppProjectsProjectSlugIndexRoute,
    AppProjectsProjectSlugArchitectureIndexRoute:
      AppProjectsProjectSlugArchitectureIndexRoute,
    AppProjectsProjectSlugIntegrationsIndexRoute:
      AppProjectsProjectSlugIntegrationsIndexRoute,
    AppProjectsProjectSlugSettingsIndexRoute:
      AppProjectsProjectSlugSettingsIndexRoute,
    AppProjectsProjectSlugResourcesResourceSlugIndexRoute:
      AppProjectsProjectSlugResourcesResourceSlugIndexRoute,
  }

const AppProjectsProjectSlugRouteWithChildren =
  AppProjectsProjectSlugRoute._addFileChildren(
    AppProjectsProjectSlugRouteChildren,
  )

interface AppRouteChildren {
  AppConsentRoute: typeof AppConsentRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectSlugRoute: typeof AppProjectsProjectSlugRouteWithChildren
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
  AppSettingsOrganizationRoute: typeof AppSettingsOrganizationRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppMembersIndexRoute: typeof AppMembersIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConsentRoute: AppConsentRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectSlugRoute: AppProjectsProjectSlugRouteWithChildren,
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
  AppSettingsOrganizationRoute: AppSettingsOrganizationRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppMembersIndexRoute: AppMembersIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthedRouteChildren {
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOnboardingRoute: AuthedOnboardingRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
  DeviceRoute: DeviceRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
