// AUTO-GENERATED by scripts/gen-canvas-nodes.ts — do not edit.
// Run `bun run gen:canvas-nodes` to regenerate.
// @generated

import type { NodeProps } from "@xyflow/react"
import type { ComponentType } from "react"

export type CanvasNodeComponent = ComponentType<NodeProps>

export const customNodes: Record<string, CanvasNodeComponent> = {
	// populated when files like aws_rds_cluster.tsx exist in this dir
}
