// AUTO-GENERATED by scripts/gen-policy-registry.ts — do not edit.
// Run `bun run gen:policies` to regenerate.
// @generated

import type { PolicyDef } from "@opsy/provider"
import alwaysPolicy from "./always"
import onDestroyPolicy from "./on-destroy"

export const policyRegistry: Record<string, PolicyDef> = {
	always: alwaysPolicy,
	on_destroy: onDestroyPolicy,
}
