/**
 * @generated — do not edit this script output; edit this script instead.
 *
 * Generates: src/policies/registry.generated.ts
 *
 * Run via: bun run gen:policies
 * Idempotent: running twice produces no diff.
 */

import { readFileSync, writeFileSync } from "node:fs"
import { basename, join } from "node:path"
import { snakeToCamel } from "./utils"

const EXCLUDE = new Set(["policies.ts", "registry.generated.ts", "kinds.ts"])

const policiesDir = join(import.meta.dir, "../src/policies")
const glob = new Bun.Glob("*.ts")
const files = Array.from(glob.scanSync(policiesDir))
	.filter((f) => !EXCLUDE.has(f))
	.sort()

// Parse the `id` string from the definePolicy({ id: "..." }) call in each
// policy file so that registry keys match the stored DB value, not the
// file stem (which may differ after kebab-case renames).
function parsePolicyId(filePath: string): string {
	const src = readFileSync(filePath, "utf8")
	const match = src.match(/definePolicy\s*\(\s*\{[^}]*?id:\s*["']([^"']+)["']/)
	if (!match) throw new Error(`Could not parse policy id from ${filePath}`)
	return match[1]
}

const lines: string[] = [
	"// AUTO-GENERATED by scripts/gen-policy-registry.ts — do not edit.",
	"// Run `bun run gen:policies` to regenerate.",
	"// @generated",
	"",
	'import type { PolicyDef } from "@opsy/provider"',
]

const entries: Array<{ key: string; varName: string; stem: string }> = []
for (const file of files) {
	const stem = basename(file, ".ts")
	const key = parsePolicyId(join(policiesDir, file))
	const varName = `${snakeToCamel(key)}Policy`
	entries.push({ key, varName, stem })
	lines.push(`import ${varName} from "./${stem}"`)
}

lines.push("")
lines.push("export const policyRegistry: Record<string, PolicyDef> = {")
for (const { key, varName } of entries) {
	lines.push(`	${key}: ${varName},`)
}
lines.push("}")
lines.push("")

const content = lines.join("\n")
const outPath = join(policiesDir, "registry.generated.ts")
writeFileSync(outPath, content)
console.log(`Wrote ${outPath}`)
