import { pgTable, timestamp, uuid } from "drizzle-orm/pg-core"
import { organization } from "./auth"

// One row per organization marks its onboarding checklist as completed.
// Row presence (not a boolean column on `organization`) so the auth.ts file —
// which is regenerated by the Better Auth CLI — stays untouched. PK lookup is
// the only read, and after completion the checklist UI never queries derived
// task state again.
export const onboardingCompletions = pgTable("onboarding_completions", {
	organizationId: uuid("organization_id")
		.primaryKey()
		.references(() => organization.id, { onDelete: "cascade" }),
	completedAt: timestamp("completed_at", { withTimezone: true })
		.defaultNow()
		.notNull(),
})
